### PR TITLE
Move model asset to production COS link

### PR DESCRIPTION
**Pull request by xuhdev**

### CODE REVIEW

**Review by bdwyer2 — COMMENTED** [review]
Looks like the file is set to private. Once you fix it on COS you can close then re-open this PR to trigger another Travis build

**Comment by xuhdev** [comment]
Will delete the dev file once this is merged

**Comment by bdwyer2** [comment]
@xuhdev maybe we should keep the dev for now in case someone isn't using up to date code?

**Review by bdwyer2 — APPROVED** [review]

**Comment by xuhdev** [comment]
Right - v1.0.0 is using it.

**Pull request merged**
